name: query_client
description: A easy to use query client to manipulate api and UI.
repository: https://github.com/AielloChan/query_client
version: 1.0.1

environment:
  sdk: ">=2.12.0 < 4.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
