name: query_client
description: A user-friendly query client for seamless API and UI manipulation.
repository: https://github.com/AielloChan/query_client
version: 1.2.0

environment:
  sdk: ">=2.12.0 < 4.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
